#!/bin/bash

# Record teleop episodes with DK-1 using RT impedance control.
#
# Usage:
#   ./record_episode.sh             # start new dataset
#   ./record_episode.sh --resume    # continue existing dataset
#
# Run: python examples/identify_ports.py to generate port_config.env

# Stable port mappings (generated by examples/identify_ports.py)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../port_config.env"

RESUME=false
if [ "$1" = "--resume" ]; then
    RESUME=true
fi

uv run lerobot-record \
    --resume=$RESUME \
    --robot.type=dk1_follower \
    --robot.port=$LEFT_FOLLOWER \
    --robot.control_mode=rt_impedance \
    --teleop.type=dk1_leader \
    --teleop.port=$LEFT_LEADER \
    --robot.cameras="{
        context: {type: opencv, index_or_path: $CONTEXT_CAM, width: 1280, height: 720, fps: 60, fourcc: MJPG},
        wrist: {type: opencv, index_or_path: $WRIST_LEFT, width: 1280, height: 720, fps: 60, rotation: 180, fourcc: MJPG}
      }" \
    --dataset.repo_id=${USER}/dk1_pick_cube \
    --dataset.num_episodes=10 \
    --dataset.episode_time_s=30 \
    --dataset.reset_time_s=15 \
    --dataset.single_task="Pick up the red cube and place it in the bin." \
    --dataset.vcodec=auto \
    --dataset.streaming_encoding=true \
    --dataset.encoder_threads=2 \
    --dataset.push_to_hub=false \
    --display_data=true
