#!/bin/bash

# Record bimanual teleop episodes with DK-1 using RT impedance control.
#
# Usage:
#   ./record_episode_bimanual.sh             # start new dataset
#   ./record_episode_bimanual.sh --resume    # continue existing dataset
#
# Run: python examples/identify_ports.py -m bimanual to generate port_config.env

# Stable port mappings (generated by examples/identify_ports.py)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../port_config.env"

RESUME=false
if [ "$1" = "--resume" ]; then
    RESUME=true
fi

uv run lerobot-record \
    --resume=$RESUME \
    --robot.type=bi_dk1_follower \
    --robot.control_mode=rt_impedance \
    --robot.right_arm_port=$RIGHT_FOLLOWER \
    --robot.left_arm_port=$LEFT_FOLLOWER \
    --teleop.type=bi_dk1_leader \
    --teleop.right_arm_port=$RIGHT_LEADER \
    --teleop.left_arm_port=$LEFT_LEADER \
    --robot.cameras="{
        head: {type: opencv, index_or_path: $CONTEXT_CAM, width: 1280, height: 720, fps: 60, fourcc: MJPG},
        right_wrist: {type: opencv, index_or_path: $WRIST_RIGHT, width: 1280, height: 720, fps: 60, rotation: 180, fourcc: MJPG},
        left_wrist: {type: opencv, index_or_path: $WRIST_LEFT, width: 1280, height: 720, fps: 60, rotation: 180, fourcc: MJPG}
      }" \
    --dataset.repo_id=${USER}/dk1_fold_towels_002 \
    --dataset.num_episodes=10 \
    --dataset.episode_time_s=120 \
    --dataset.reset_time_s=15 \
    --dataset.single_task="Pick up a towel and fold it." \
    --dataset.vcodec=h264 \
    --dataset.streaming_encoding=false \
    --dataset.encoder_threads=4 \
    --dataset.push_to_hub=false \
    --display_data=true
